_To create vector from dict:_

In [13]:
data = [{'#courses_opted': 4, 'GPA': 6.7},
        {'#courses_opted': 4, 'GPA': 8.5},
        {'#courses_opted': 2, 'GPA': 8.1},
        {'#courses_opted': 1, 'GPA': 7.2},
        {'#courses_opted': 1, 'GPA': 9.1}]

In [2]:
from sklearn.feature_extraction import DictVectorizer
dv = DictVectorizer(sparse=False)
data_trans = dv.fit_transform(data)
data_trans

array([[4. , 6.7],
       [4. , 8.5],
       [2. , 8.1],
       [1. , 7.2],
       [1. , 9.1]])

MaxAbsScalar: $ x' = {x \over MaxAbsValue} $

In [3]:
from sklearn.preprocessing import MaxAbsScaler
Y = [[2],[8],[-4]]
mas = MaxAbsScaler()
mas.fit_transform(Y)

array([[ 0.25],
       [ 1.  ],
       [-0.5 ]])

_Function Transformer uses user-defined function_

In [2]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

In [5]:
X=np.array([[1],[2],[3]])
ft = FunctionTransformer(np.mean)
ft.fit_transform(X)

2.0

_OneHotEncoder: One binary column for each of unique values_

In [12]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
ohe = OneHotEncoder()

In [8]:
X = np.array([[4],[3],[2],[3],[1]])
ohe.fit_transform(X)

<5x4 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

_MultiLabelBinarizer encodes categorical features w/ values b/w $ {K-1} $ and $ K $._

In [9]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()

In [12]:
X = np.array([['Heart-disease', 'Diabetes'],['High-BP'],['Heart-disease','High-BP'],['Diabetes']], dtype=object)
mlb.fit_transform(X)

array([[1, 1, 0],
       [0, 0, 1],
       [0, 1, 1],
       [1, 0, 0]])

_Variance Threshold defaults to remove feature (column) with zero variance._

In [1]:
from sklearn.feature_selection import VarianceThreshold

In [8]:
X = np.array([[1,1,1],[1,3,4],[1,2,4]])

vt = VarianceThreshold()
vt.fit_transform(X)

array([[1, 1],
       [3, 4],
       [2, 4]])

In [11]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.compose import ColumnTransformer

In [13]:
X = np.array([[1,'yes'],[2,'no'],[3,'no']])

ct = ColumnTransformer([('scaler', MinMaxScaler(),[0]),
                        ('pass', 'passthrough', [0]),
                        ('encoder', OrdinalEncoder(), [1])])

ct.fit_transform(X)

array([['0.0', '1', '1.0'],
       ['0.5', '2', '0.0'],
       ['1.0', '3', '0.0']], dtype='<U32')