# Matrices


## Import

In [1]:
import numpy as np

## Matrix as a `NumPy` array

Everything in `NumPy` is an array. A matrix is also an array. Let us create a simple matrix:

$$
\textbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}
$$

In `NumPy`:

In [2]:
M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Adding two matrices

Let us now add the following matrices:

$$
\textbf{A} = \begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}, \textbf{B} = \begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}
$$

then,

$$
\textbf{C} = \textbf{A} + \textbf{B}  = \begin{bmatrix}
6 & 8\\
10 & 12
\end{bmatrix}
$$

In `NumPy`:

In [3]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[5,6],
              [7,8]])
C = A + B
C

array([[ 6,  8],
       [10, 12]])

## Scaling a matrix

Scaling a matrix is nothing but element-wise multiplication:

$$
\textbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}
$$

then, 

$$
3 \textbf{M} = \begin{bmatrix}
3 & 6 & 9\\
12 & 15 & 18\\
21 & 24 & 27
\end{bmatrix}
$$

In `NumPy`:

In [4]:
M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
3 * M

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

## Element-wise multiplication of matrices

Consider two matrices:

$$
\textbf{A} = \begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}, \textbf{B} = \begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}
$$

The element-wise product is given by $\textbf{A} \odot \textbf{B}$:

$$
\textbf{C} = \textbf{A} \odot \textbf{B} = \begin{bmatrix}
5 & 12\\
21 & 32
\end{bmatrix}
$$

In `NumPy`:

In [5]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[5,6],
              [7,8]])
C = A * B
C

array([[ 5, 12],
       [21, 32]])

## Element-wise functions of matrices

Given a matrix, we sometimes would want to apply a function to every element of the matrix. We will consider two examples.

### Example-1

For example, we may want to take the absolute value of all the elements. Let us say $f(x) = |x|$, then:

$$
\mathbf{A} = \begin{bmatrix}
-1 & 2\\
-3 & -4
\end{bmatrix}
$$

then:

$$
\begin{bmatrix}
f(-1) & f(2)\\
f(-3) & f(-4)
\end{bmatrix} = 
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}
$$

In `NumPy`, this becomes:

In [6]:
A = np.array([[-1,2],
              [-3,-4]])
np.abs(A)

array([[1, 2],
       [3, 4]])

### Example-2

We might want to square each element of the matrix. If $\textbf{A}$ is a matrix, then $\textbf{B}$ could be defined element-wise as follows:

$$
B_{ij} = A_{ij}^2
$$

Let us compute $\mathbf{B}$ for the following matrix:

$$
\mathbf{A} = \begin{bmatrix}
1 & \sqrt{2}\\
\sqrt{3} & 2
\end{bmatrix}
$$

In `NumPy`:

In [8]:
A = np.array([[1,np.sqrt(2)],
              [np.sqrt(3),2]])
A ** 2

array([[1., 2.],
       [3., 4.]])

## Transpose of a matrix

Given a matrix $\textbf{M}$:

$$
\textbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}
$$

then, its transpose $\textbf{M}^{T}$ is:

$$
\textbf{M}^{T} = \begin{bmatrix}
1 & 4\\
2 & 5\\
3 & 6
\end{bmatrix}
$$

In `NumPy`:

In [11]:
M = np.array([[1,2,3],
              [4,5,6]])
np.transpose(M)
#   OR
M.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Product of two matrices

Given two matrices:

$$
\textbf{A} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}, \textbf{B} = \begin{bmatrix}
6 & 7\\
8 & 9\\
10 & 11
\end{bmatrix}
$$

then,

$$
\textbf{C} = \textbf{A} \times \textbf{B} = \begin{bmatrix}
52 & 58\\
124 & 139
\end{bmatrix}
$$

In `NumPy`:

In [17]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[6,7],
              [8,9],
              [10,11]])
np.dot(A,B)
#     OR
A @ B
#     OR
np.matmul(A,B)

array([[ 52,  58],
       [124, 139]])

## Product of a matrix and a vector

Given the matrix $\mathbf{A}$ and the vector $\mathbf{x}$:

$$
\mathbf{A} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}, \mathbf{x} = \begin{bmatrix}
6\\
7\\
8
\end{bmatrix}
$$

The product $\mathbf{Ax}$ is given by:

$$
\mathbf{C} = \mathbf{A x} = \begin{bmatrix}
44\\
107\\
170
\end{bmatrix}
$$

In `NumPy`:

In [16]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
x = np.array([6,7,8])
C = A @ x
C

array([ 44, 107, 170])

## Matrix of zeros

In many algorithms, we might have to initialize a matrix with zeros. For example, consider a $2 \times 4$ matrix:

$$
\mathbf{M} = \begin{bmatrix}
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{bmatrix}
$$

In `NumPy`:

In [20]:
M = np.zeros((2,4))
M

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Matrix of ones

Similar to a matrix of zeros, we can come up with a matrix of ones. 

$$
\mathbf{M} = \begin{bmatrix}
1 & 1\\
1 & 1\\
1 & 1
\end{bmatrix}
$$

In `NumPy`:

In [21]:
M = np.ones((3,2))
M

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## Identity matrix

Often, we might have to deal with identity matrices. A $3 \times 3$ identity matrix is as follows:

$$
\mathbf{I} = \begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{bmatrix}
$$

In `NumPy`:

In [23]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Diagonal matrices

Another special kind of matrix. Let us create the following matrix:

$$
\mathbf{D} = \begin{bmatrix}
1 & 0 & 0 & 0\\
0 & 2 & 0 & 0\\
0 & 0 & 3 & 0\\
0 & 0 & 0 & 4
\end{bmatrix}
$$

In `NumPy`:

In [27]:
D = np.diag([1,2,3,4])
D

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## Shape and dimension of a matrix

Matrices are "two dimensional" arrays. So all matrices in `NumPy` have array-dimension equal to two. The shape of the `NumPy` array gives what we usually call the dimension of the matrix in the linear algebra sense.

Explore these two ideas for:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
\end{bmatrix}
$$

In `NumPy`:

In [25]:
M = np.array([[1,2,3],
              [4,5,6]])
M.shape, M.ndim

((2, 3), 2)